version: '3'
services:
  python3:
    build: .
    container_name: 'dockerKeeper'
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    environment:
      - DISPLAY=host.docker.internal:0